name = "sms-panel"
main = "src/worker.js"
compatibility_date = "2026-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

# این بخش رو بعد از دیپلوی اول، از داشبورد کلادفلر (تب Bindings) هم می‌تونی اضافه/تأیید کنی.
# اگه دیتابیس رو با اسم دیگه‌ای ساختی، همون اسم رو جای smspanel بذار.
[[d1_databases]]
binding = "DB"
database_name = "smspanel"
database_id = "5407dd04-0544-4410-ae44-6d5e4d3fcc5e"
